function new-site-php -a name -d "Makes new PHP site"
  switch "$name"
  case ''
    crow notice "Usage: new-php-html <name>"
  case '*'

    site-file-structure $name 

    crow notice "Generating files"

    cp /cocky/templates/php/index.php /cocky/sites/$name/public
    cp /cocky/templates/php/header.php /cocky/sites/$name/public/inc
    cp /cocky/templates/css/noralize.css /cocky/sites/$name/public/css
    cp /cocky/templates/css/style.css /cocky/sites/$name/public/css

    crow notice "Setting up initial nginx configuration"
    cd /cocky/sites/$name

    echo "# GENERATED by new-site-php" > config/nginx.conf
    echo "server {" >> config/nginx.conf
    echo " listen 80;" >> config/nginx.conf
    echo -s " server_name " $name "." (hostname) ";" >> config/nginx.conf
    echo -s " root /cocky/sites/" $name "/public;" >> config/nginx.conf
    echo " index index.php index.html index.htm;" >> config/nginx.conf
    echo " # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000" >> config/nginx.conf
    echo ' location ~ \.php$ {' >> config/nginx.conf
    echo '   try_files $uri =404;' >> config/nginx.conf
    echo '   fastcgi_pass unix:/var/run/php5-fpm.sock;' >> config/nginx.conf
    echo '   fastcgi_index index.php;' >> config/nginx.conf
    echo '   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> config/nginx.conf
    echo '   include fastcgi_params;' >> config/nginx.conf
    echo ' }' >> config/nginx.conf
    echo "}" >> config/nginx.conf

    rweb
    crow success "Site ready"
  
  editor public/index.php
 end
end
