function new-site-rails

 cd /devstar/sites
 mkdir $argv[1]
 cd $argv[1]
 rails new . -B
 cp /devstar/config/gemfile ./Gemfile

 echo "# GENERATED by new-site-rails" > config/nginx.conf
 echo "server {" >> config/nginx.conf
 echo " listen 80;" >> config/nginx.conf
 echo -s " server_name " $argv[1] "." (hostname) ";" >> config/nginx.conf
 echo -s " root /devstar/sites/" $argv[1] "/public;" >> config/nginx.conf
 echo " passenger_enabled on;" >> config/nginx.conf
 echo " rack_env development;" >> config/nginx.conf
 echo "}" >> config/nginx.conf

 echo ""
 editor Gemfile
 bundle install
 rake db:create
 rweb

 crow success "Site $argv[1] is now ready"

end
