function new-site-html -a name -d "Makes new HTML site"
  switch "$name"
  case ''

    crow error "Usage: new-site-html <name>"

  case '*'

    site-file-structure $name

    crow notice "Generating files"
    cp /cocky/templates/html/index.html /cocky/sites/$name/public
    cp /cocky/templates/css/normalize.css /cocky/sites/$name/public/css
    cp /cocky/templates/css/style.css /cocky/sites/$name/public/css
    cd /cocky/sites/$name

    echo "# GENERATED by new-site-html" > config/nginx.conf
    echo "server {" >> config/nginx.conf
    echo " listen 80;" >> config/nginx.conf
    echo -s " server_name " $name "." (hostname) ";" >> config/nginx.conf
    echo -s " root /cocky/sites/" $name "/public;" >> config/nginx.conf
    echo "}" >> config/nginx.conf

    crow notify "Restarting webserver"
    rweb
  
    crow success "Site ready"  
    editor public/index.html
  end
end
