function new-site-php -a name -d "Makes new PHP site"
  switch "$name"
  case ''
    crow notice "Usage: new-php-html <name>"
  case '*'

    site-file-structure $name

    crow notice "Generating files"

    cp /devstar/templates/php/index.php /devstar/sites/$name/public
    cp /devstar/templates/php/header.php /devstar/sites/$name/public/inc
    cp /devstar/templates/css/normalize.css /devstar/sites/$name/public/css
    cp /devstar/templates/css/style.css /devstar/sites/$name/public/css

    crow notice "Setting up initial nginx configuration"
    cd /devstar/sites/$name

    touch log/nginx.access.log
    touch log/nginx.error.log

    echo "# GENERATED by new-site-php" > config/nginx.conf
    echo "server {" >> config/nginx.conf
    echo " listen 80;" >> config/nginx.conf
    echo -s " server_name " $name "." (hostname) ";" >> config/nginx.conf
    echo -s " root /devstar/sites/" $name "/public;" >> config/nginx.conf
    echo -s " access_log /devstar/sites/" $name "/log/nginx.access.log;" >> config/nginx.conf;
    echo -s " error_log /devstar/sites/" $name "/log/nginx.error.log;" >> config/nginx.conf;
    echo " index index.php index.html index.htm;" >> config/nginx.conf
    echo " # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000" >> config/nginx.conf
    echo ' location ~ \.php$ {' >> config/nginx.conf
    echo '   try_files $uri =404;' >> config/nginx.conf
    echo '   fastcgi_pass unix:/var/run/php5-fpm.sock;' >> config/nginx.conf
    echo '   fastcgi_index index.php;' >> config/nginx.conf
    echo '   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> config/nginx.conf
    echo '   include fastcgi_params;' >> config/nginx.conf
    echo ' }' >> config/nginx.conf
    echo "}" >> config/nginx.conf

    rweb
    crow success "Site ready"

  editor public/index.php
 end
end