function new-site-html -a name -d "Makes new HTML site"
  switch "$name"
  case ''

    crow error "Usage: new-site-html <name>"

  case '*'

    skeletons default html
    cd /devstar/sites/$name

    echo "# GENERATED by new-site-html" > config/nginx.conf
    echo "server {" >> config/nginx.conf
    echo " listen 80;" >> config/nginx.conf
    echo -s " server_name " $name "." (hostname) ";" >> config/nginx.conf
    echo -s " error_page 404 /404.html"
    echo -s " error_page 500 501 502 503 504 /50x.html"
    echo -s " root /devstar/sites/" $name "/public;" >> config/nginx.conf
    echo "}" >> config/nginx.conf

    crow notify "Restarting webserver"
    rweb
  
    crow success "Site ready"  
    editor public/index.html
  end
end
